---
- name: timedatectl set-ntp false
  command: timedatectl set-ntp false 

- name: install openntpd
  yum:
    pkg: openntpd
    state: installed
  notify: start openntpd

- name: enabled openntpd
  systemd:
    name: openntpd
    enabled: yes

